apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: batel-nginx-ecr-git
  namespace: argocd
spec:
  project: default
  sources:

    - repoURL: https://github.com/BatelDayan/values_cd.git
      path: .
      targetRevision: HEAD
      ref: values

    - repoURL: 314525640319.dkr.ecr.il-central-1.amazonaws.com
      chart: "batel-nginx"
      targetRevision: 0.1.0
      helm:
        valueFiles:
          - $values/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: batel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false