apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: batel-nginx-ecr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 314525640319.dkr.ecr.il-central-1.amazonaws.com
    chart: "batel-nginx"
    targetRevision: 0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: batel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
