apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: 80
      targetPort: {{ .Values.image.port }}
  type: {{ .Values.service.type }}
