name: Build and Deploy to EKS

on:
#  push:
#    paths:
#      - Dockerfile
#      - index.html
#    branches:
#      - main

  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: batel123d/batel-basic-web
      EKS_CLUSTER: imtech01
      REGION: il-central-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $REGION --name $EKS_CLUSTER

      - name: Helm upgrade
        run: |
          helm upgrade --install batel-ci-cd ./batel-helm \
            --set image.repository=$IMAGE_NAME \
            --set image.tag=latest \
            --namespace batel
